# Generated by Django 5.1.6 on 2025-04-27 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAcademy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_academy/%Y/%m/')),
            ],
            options={
                'verbose_name': 'akademiya haqida',
                'verbose_name_plural': 'akademiya haqida',
            },
        ),
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_company/%Y/%m/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Klub haqida',
                'verbose_name_plural': 'klub haqida',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='banners/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='coaches/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='coaches_banners/%Y/%m/')),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=255)),
                ('coach_type', models.CharField(choices=[('akademik murabbiy', 'Akademik murabbiy'), ('jamoa murabbiy', 'Jamoa murabbiy')], default='jamoa murabbiy', max_length=255)),
            ],
            options={
                'verbose_name': 'murabbiylar',
                'verbose_name_plural': 'murabbiylar',
            },
        ),
        migrations.CreateModel(
            name='CoachPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'murabbiy pozitsiyasi',
                'verbose_name_plural': 'murabbiy pozitsiyalari',
            },
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='leaders/%Y/%m/')),
                ('birth_date', models.DateField()),
            ],
            options={
                'verbose_name': 'raxbariyat',
                'verbose_name_plural': 'raxbariyat',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'yangilik turi',
                'verbose_name_plural': 'yangilik turlari',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='partners/%Y/%m/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'hamkor',
                'verbose_name_plural': 'hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='PlayerCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ImageField(upload_to='flags/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'futbolchi mamlakati',
                'verbose_name_plural': 'futbolchi mamlakatlari',
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'futbolchi pozisiyasi',
                'verbose_name_plural': 'futbolchi pozisiyalari',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stadiums/%Y/%m/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'stadion haqida',
                'verbose_name_plural': 'stadionlar haqida',
            },
        ),
        migrations.CreateModel(
            name='CoachInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('value_en', models.CharField(max_length=255, null=True)),
                ('value_ru', models.CharField(max_length=255, null=True)),
                ('value_uz', models.CharField(max_length=255, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='common.coach')),
            ],
            options={
                'verbose_name': 'murabbiy malumoti',
                'verbose_name_plural': 'murabbiy malumotlari',
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='common.coachposition'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('title_uz', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='news/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/%Y/%m/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='common.newscategory')),
            ],
            options={
                'verbose_name': 'yangiliklar',
                'verbose_name_plural': 'yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='players/%Y/%m/')),
                ('number', models.PositiveIntegerField()),
                ('goal', models.IntegerField()),
                ('match', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('height', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak'), ('U19', 'U19'), ('U21', 'U21')], max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='common.playercountry')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='common.playerposition')),
            ],
            options={
                'verbose_name': 'futbolchi',
                'verbose_name_plural': 'futbolchilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
