# Generated by Django 5.1.6 on 2025-04-27 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='description',
        ),
        migrations.RemoveField(
            model_name='players',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='players',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='players',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='news_media')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='common.news')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
