# Generated by Django 5.1.6 on 2025-04-27 20:00

from django.db import migrations
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_players_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='news_media')),
                ('news', models.ForeignKey(on_delete=models.CASCADE, related_name='medias', to='your_app.News')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
