# Generated by Django 5.1.6 on 2025-04-27 20:09

from django.db import migrations, models


def add_link_to_news(apps, schema_editor):
    News = apps.get_model('common', 'News')
    News.add_to_class('link', models.URLField(null=True, blank=True))

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20250427_2000'),
    ]

    operations = [
        migrations.RunPython(add_link_to_news),
    ]